######################################################################
# Automatically generated by qmake (3.0) Wed Dec 7 18:34:57 2016
######################################################################

TEMPLATE = app
TARGET = ras
INCLUDEPATH += .
QT += widgets
CONFIG += c++11


# Input
HEADERS += circlewidget.h getdata.h getSocket.h window.h
SOURCES += circlewidget.cpp getdata.cpp main.cpp window.cpp
RESOURCES += picture/res.qrc
